import assert from 'node:assert/strict'
import test from 'node:test'
import { existsSync, readFileSync } from 'node:fs'
import { join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = fileURLToPath(new URL('..', import.meta.url))
const android = join(root, 'android')
const read = (...parts: string[]) => readFileSync(join(android, ...parts), 'utf8')

test('Android project has a reproducible Gradle application contract', () => {
  for (const path of [
    ['settings.gradle.kts'], ['build.gradle.kts'], ['gradle.properties'], ['gradlew'], ['gradlew.bat'],
    ['gradle', 'wrapper', 'gradle-wrapper.properties'], ['app', 'build.gradle.kts'], ['app', 'src', 'main', 'AndroidManifest.xml'],
  ]) assert.equal(existsSync(join(android, ...path)), true, `missing android/${path.join('/')}`)
  const appGradle = read('app', 'build.gradle.kts')
  assert.match(appGradle, /compileSdk\s*=\s*35/)
  assert.match(appGradle, /minSdk\s*=\s*26/)
  assert.match(appGradle, /targetSdk\s*=\s*35/)
  assert.match(read('gradle', 'wrapper', 'gradle-wrapper.properties'), /gradle-8\.9-bin\.zip/)
  assert.match(read('gradle', 'wrapper', 'gradle-wrapper.properties'), /distributionSha256Sum=d725d707bfabd4dfdc958c624003b3c80accc03f7037b5122c4b1d0ef15cecab/)
  assert.match(read('gradlew'), /\$JAVA_HOME\/bin\/java/)
  assert.match(read('gradlew.bat'), /%JAVA_HOME%\/bin\/java\.exe/)
  assert.match(read('.gitignore'), /local\.properties/)
  assert.match(read('.gitignore'), /\*\.jks/)
  assert.match(readFileSync(join(root, '.gitignore'), 'utf8'), /\.toolchains\//)
})

test('Android manifest and trusted WebView fail closed around the Javascript bridge', () => {
  const manifest = read('app', 'src', 'main', 'AndroidManifest.xml')
  const activity = read('app', 'src', 'main', 'java', 'ai', 'stagecraft', 'android', 'MainActivity.java')
  const client = read('app', 'src', 'main', 'java', 'ai', 'stagecraft', 'android', 'LocalAssetWebViewClient.java')
  const html = read('app', 'src', 'main', 'assets', 'index.html')
  const renderer = read('app', 'src', 'main', 'assets', 'renderer.js')
  assert.match(manifest, /android\.permission\.INTERNET/)
  assert.match(manifest, /android:allowBackup="false"/)
  assert.doesNotMatch(manifest, /android:debuggable="true"/)
  assert.match(activity, /ApplicationInfo\.FLAG_DEBUGGABLE/)
  assert.match(activity, /setWebContentsDebuggingEnabled\(debuggable\)/)
  for (const setting of ['setAllowFileAccess(false)', 'setAllowContentAccess(false)', 'setDomStorageEnabled(false)', 'setMixedContentMode(WebSettings.MIXED_CONTENT_NEVER_ALLOW)']) assert.ok(activity.includes(setting))
  assert.match(activity, /setAcceptCookie\(false\)/)
  assert.match(client, /appassets\.androidplatform\.net/)
  assert.match(client, /request\.isForMainFrame\(\)/)
  assert.match(client, /return forbidden\(\)/)
  assert.match(html, /frame-src 'none'/)
  assert.doesNotMatch(renderer, /structuredClone/)
  assert.doesNotMatch(html, /<iframe/i)
  assert.doesNotMatch(html, /(?:src|href)="https?:\/\//i)
})

test('legacy card WebView is isolated, origin-pinned, and has no native bridge', () => {
  const policy = read('app', 'src', 'main', 'java', 'ai', 'stagecraft', 'android', 'LegacyWebViewPolicy.java')
  assert.match(policy, /setAllowFileAccess\(false\)/)
  assert.match(policy, /setAllowUniversalAccessFromFileURLs\(false\)/)
  assert.match(policy, /setAcceptCookie\(false\)/)
  assert.match(policy, /connect-src|isAllowed/)
  assert.match(policy, /appassets\.androidplatform\.net/)
  assert.match(policy, /getQueryParameterNames/)
  assert.doesNotMatch(policy, /addJavascriptInterface/)
  assert.doesNotMatch(policy, /HttpURLConnection|FileInputStream|StageCraftNative/)
})

test('Android cleartext access requires the explicit UI risk switch and strict native validation', () => {
  const manifest = read('app', 'src', 'main', 'AndroidManifest.xml')
  const html = read('app', 'src', 'main', 'assets', 'index.html')
  const renderer = read('app', 'src', 'main', 'assets', 'renderer.js')
  const validator = read('app', 'src', 'main', 'java', 'ai', 'stagecraft', 'android', 'ServerAddressValidator.java')
  assert.match(manifest, /android:usesCleartextTraffic="true"/)
  assert.match(html, /value="https:\/\/"/)
  assert.match(html, /id="allow-http" type="checkbox"/)
  assert.match(html, /HTTP 不加密/)
  assert.ok(renderer.includes("bridge.pair(byId('server-address').value.trim(), byId('allow-http').checked"))
  assert.match(validator, /scheme\.equals\("http"\) && !allowInsecureHttp/)
  for (const forbidden of ['getUserInfo()', 'getQuery()', 'getFragment()']) assert.ok(validator.includes(forbidden))
})

test('Android credentials stay native, encrypted, and out of URLs or Javascript', () => {
  const store = read('app', 'src', 'main', 'java', 'ai', 'stagecraft', 'android', 'RemoteSessionStore.java')
  const connection = read('app', 'src', 'main', 'java', 'ai', 'stagecraft', 'android', 'RemoteCoreConnection.java')
  const bridge = read('app', 'src', 'main', 'java', 'ai', 'stagecraft', 'android', 'NativeBridge.java')
  const renderer = read('app', 'src', 'main', 'assets', 'renderer.js')
  assert.match(store, /AndroidKeyStore/)
  assert.match(store, /AES\/GCM\/NoPadding/)
  assert.match(store, /new JSONObject\(\)\.put\("address", address\).*put\("credential", credential\)/)
  assert.match(store, /session_ciphertext/)
  assert.match(store, /session_iv/)
  assert.doesNotMatch(store, /putString\([^\n]*(token|credential)/i)
  assert.match(store, /\.commit\(\)/)
  assert.match(connection, /setRequestProperty\("Authorization", "Bearer " \+ credential\)/)
  assert.match(connection, /setInstanceFollowRedirects\(false\)/)
  assert.doesNotMatch(connection, /[?&](token|session)=/i)
  assert.doesNotMatch(bridge, /(Log\.|System\.out|printStackTrace)/)
  assert.doesNotMatch(renderer, /(localStorage|document\.cookie|Bearer|token)/)
  assert.match(bridge, /JSONObject\.quote\(messageJson\)/)
})

test('built Android APK contains the verified embedded Core assets', () => {
  const apk = join(android, 'app', 'build', 'outputs', 'apk', 'debug', 'app-debug.apk')
  if (!existsSync(apk)) return
  const bytes = readFileSync(apk)
  const zipNames = bytes.toString('latin1')
  for (const asset of ['assets/embedded-core.js', 'assets/embedded-core.json', 'assets/index.html', 'assets/renderer.js']) {
    assert.ok(zipNames.includes(asset), `missing ${asset} from APK`)
  }
})

test('Android embedded Core is generated, verified, and selected locally', () => {
  const readme = readFileSync(join(android, 'README.md'), 'utf8')
  const bridge = read('app', 'src', 'main', 'java', 'ai', 'stagecraft', 'android', 'NativeBridge.java')
  const verifier = read('app', 'src', 'main', 'java', 'ai', 'stagecraft', 'android', 'EmbeddedCoreArtifact.java')
  const activity = read('app', 'src', 'main', 'java', 'ai', 'stagecraft', 'android', 'MainActivity.java')
  const operations = read('app', 'src', 'main', 'java', 'ai', 'stagecraft', 'android', 'AndroidCompositionOperations.java')
  const gradle = read('app', 'build.gradle.kts')
  const entrypoint = readFileSync(join(root, 'src', 'portable', 'android-core.ts'), 'utf8')
  assert.match(readme, /embedded-core\.js/)
  assert.match(readme, /shared StageCraft solution composition/)
  assert.match(readme, /model gateway, SQLite repository, Cordis services/)
  assert.match(bridge, /localCoreAllowed/)
  assert.match(bridge, /embeddedCore\.valid\(\)/)
  assert.match(verifier, /SHA-256/)
  assert.match(verifier, /EXPECTED_PROTOCOL/)
  assert.match(verifier, /EXPECTED_BUNDLE/)
  assert.match(activity, /EmbeddedCoreArtifact\.verify/)
  assert.match(gradle, /buildEmbeddedCore/)
  assert.match(gradle, /packageEmbeddedCore/)
  assert.match(gradle, /verifyEmbeddedCoreAssets/)
  assert.match(gradle, /SHA-256/)
  assert.match(gradle, /generated\/android-assets/)
  assert.match(gradle, /inputs\.file\(coreBuildScript\)/)
  assert.match(gradle, /inputs\.dir\(coreSourceRoot\)/)
  assert.match(gradle, /--output-dir/)
  assert.match(gradle, /embedded-core\.js.*embedded-core\.json/s)
  assert.match(gradle, /prompts\/prompts\.json/)
  assert.match(gradle, /stories\/\*\.json/)
  assert.match(entrypoint, /CoreRuntimeSkeleton/)
  assert.match(entrypoint, /StageCraftEmbeddedCore/)
  assert.match(read('app', 'src', 'main', 'assets', 'index.html'), /embedded-core\.js/)
  assert.match(read('app', 'src', 'main', 'assets', 'renderer.js'), /embedded\.start\(message => renderer\.receive\(message\)\)/)
  assert.doesNotMatch(bridge, /installLocalCore|CoreHost/)
  assert.match(operations, /stagecraft\.room\.get/)
  assert.match(operations, /stagecraft\.repository/)
  assert.match(operations, /core-state\.commit/)
})

test('Android native connection establishes SSE before view and never retries commands', () => {
  const connection = read('app', 'src', 'main', 'java', 'ai', 'stagecraft', 'android', 'RemoteCoreConnection.java')
  const openStream = connection.slice(connection.indexOf('private void openStream'), connection.indexOf('private void scheduleReconnect'))
  assert.ok(openStream.indexOf('open("/api/core/events"') < openStream.indexOf('requestView(currentGeneration)'))
  assert.ok(openStream.indexOf('emitState("connected"') < openStream.indexOf('emitResync(reason'))
  const dispatch = connection.slice(connection.indexOf('public void dispatch'), connection.indexOf('private void openStream'))
  assert.match(dispatch, /\/api\/core\/commands/)
  assert.doesNotMatch(dispatch, /scheduleReconnect|retryExecutor/)
  assert.match(connection, /backoff\.delayForAttempt/)
  assert.match(connection, /activeRequests/)
  assert.match(connection, /public synchronized void pause\(\)/)
  assert.match(connection, /public synchronized void resume\(\)/)
  assert.match(read('app', 'src', 'main', 'assets', 'renderer.js'), /bridge\.disconnect\(\)/)
  assert.match(read('app', 'src', 'main', 'assets', 'renderer.js'), /reconnecting: '正在重连'/)
})

test('Android media and PNG import remain native, bounded, authenticated, and packaged reproducibly', () => {
  const appGradle = read('app', 'build.gradle.kts')
  const connection = read('app', 'src', 'main', 'java', 'ai', 'stagecraft', 'android', 'RemoteCoreConnection.java')
  const bridge = read('app', 'src', 'main', 'java', 'ai', 'stagecraft', 'android', 'NativeBridge.java')
  const activity = read('app', 'src', 'main', 'java', 'ai', 'stagecraft', 'android', 'MainActivity.java')
  const policy = read('app', 'src', 'main', 'java', 'ai', 'stagecraft', 'android', 'RemoteAssetPolicy.java')
  const renderer = read('app', 'src', 'main', 'assets', 'renderer.js')
  assert.match(appGradle, /packageRemoteRenderer/)
  assert.match(appGradle, /include\("index\.html", "styles\.css", "renderer\.js",/)
  assert.match(appGradle, /preBuild.*dependsOn\(verifyEmbeddedCoreAssets\)/s)
  assert.match(connection, /public void loadMedia/)
  assert.match(connection, /RemoteAssetPolicy\.requireAssetPath/)
  assert.match(connection, /setInstanceFollowRedirects\(false\)/)
  assert.match(connection, /public void importCharacterCard/)
  assert.match(connection, /"\/api\/st-cards\/import"/)
  assert.match(policy, /MAX_BYTES = 2 \* 1024 \* 1024/)
  assert.match(policy, /\^\/assets\//)
  assert.doesNotMatch(policy, /svg/)
  assert.match(activity, /setType\("image\/png"\)/)
  assert.match(bridge, /isPng\(bytes\)/)
  assert.match(bridge, /8 \* 1024 \* 1024/)
  assert.match(renderer, /bridge\.loadMedia/)
  assert.match(renderer, /bridge\.chooseCharacterCard\(\)/)
  assert.doesNotMatch(renderer, /FileReader|arrayBuffer/)
})

test('desktop pairing-code operator entry is loopback-only and visible in settings', () => {
  const policy = readFileSync(join(root, 'src', 'remote-access.ts'), 'utf8')
  const html = readFileSync(join(root, 'public', 'index.html'), 'utf8')
  const app = readFileSync(join(root, 'public', 'app.js'), 'utf8')
  assert.match(policy, /\/api\/remote\/pairing-code/)
  assert.match(policy, /!isLoopbackAddress\(request\.socket\.remoteAddress\)/)
  assert.match(html, /id="remote-pairing-code"/)
  assert.match(html, /远程访问必须在启动配置中预先开启/)
  assert.match(app, /fetch\('\/api\/remote\/pairing-code', \{ method: 'POST'/)
})
