import assert from 'node:assert/strict'
import test from 'node:test'
import { existsSync, readFileSync } from 'node:fs'
import { join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = fileURLToPath(new URL('..', import.meta.url))
const android = join(root, 'android')
const read = (...parts: string[]) => readFileSync(join(android, ...parts), 'utf8')

test('Android project has a reproducible Gradle application contract', () => {
  for (const path of [
    ['settings.gradle.kts'], ['build.gradle.kts'], ['gradle.properties'], ['gradlew'], ['gradlew.bat'],
    ['gradle', 'wrapper', 'gradle-wrapper.properties'], ['app', 'build.gradle.kts'], ['app', 'src', 'main', 'AndroidManifest.xml'],
  ]) assert.equal(existsSync(join(android, ...path)), true, `missing android/${path.join('/')}`)
  const appGradle = read('app', 'build.gradle.kts')
  assert.match(appGradle, /compileSdk\s*=\s*35/)
  assert.match(appGradle, /minSdk\s*=\s*26/)
  assert.match(appGradle, /targetSdk\s*=\s*35/)
  assert.match(read('gradle', 'wrapper', 'gradle-wrapper.properties'), /gradle-8\.9-bin\.zip/)
  assert.match(read('gradle', 'wrapper', 'gradle-wrapper.properties'), /distributionSha256Sum=d725d707bfabd4dfdc958c624003b3c80accc03f7037b5122c4b1d0ef15cecab/)
  assert.match(read('gradlew'), /\$JAVA_HOME\/bin\/java/)
  assert.match(read('gradlew.bat'), /%JAVA_HOME%\/bin\/java\.exe/)
  assert.match(read('.gitignore'), /local\.properties/)
  assert.match(read('.gitignore'), /\*\.jks/)
  assert.match(readFileSync(join(root, '.gitignore'), 'utf8'), /\.toolchains\//)
})

test('Android manifest and trusted WebView fail closed around the Javascript bridge', () => {
  const manifest = read('app', 'src', 'main', 'AndroidManifest.xml')
  const activity = read('app', 'src', 'main', 'java', 'ai', 'stagecraft', 'android', 'MainActivity.java')
  const client = read('app', 'src', 'main', 'java', 'ai', 'stagecraft', 'android', 'LocalAssetWebViewClient.java')
  const html = read('app', 'src', 'main', 'assets', 'index.html')
  const renderer = read('app', 'src', 'main', 'assets', 'renderer.js')
  assert.match(manifest, /android\.permission\.INTERNET/)
  assert.match(manifest, /android:allowBackup="false"/)
  assert.doesNotMatch(manifest, /android:debuggable="true"/)
  assert.match(activity, /ApplicationInfo\.FLAG_DEBUGGABLE/)
  assert.match(activity, /setWebContentsDebuggingEnabled\(debuggable\)/)
  assert.match(activity, /onJsPrompt/)
  assert.match(activity, /result\.confirm\(input\.getText\(\)\.toString\(\)\)/)
  for (const setting of ['setAllowFileAccess(false)', 'setAllowContentAccess(false)', 'setDomStorageEnabled(false)', 'setMixedContentMode(WebSettings.MIXED_CONTENT_NEVER_ALLOW)']) assert.ok(activity.includes(setting))
  assert.match(activity, /setAcceptCookie\(false\)/)
  assert.match(client, /appassets\.androidplatform\.net/)
  assert.match(client, /request\.isForMainFrame\(\)/)
  assert.match(client, /return forbidden\(\)/)
  assert.match(html, /frame-src 'none'/)
  assert.doesNotMatch(renderer, /structuredClone/)
  assert.doesNotMatch(html, /<iframe/i)
  assert.doesNotMatch(html, /(?:src|href)="https?:\/\//i)
})

test('legacy card WebView is isolated, origin-pinned, and has no native bridge', () => {
  const policy = read('app', 'src', 'main', 'java', 'ai', 'stagecraft', 'android', 'LegacyWebViewPolicy.java')
  assert.match(policy, /setAllowFileAccess\(false\)/)
  assert.match(policy, /setAllowUniversalAccessFromFileURLs\(false\)/)
  assert.match(policy, /setAcceptCookie\(false\)/)
  assert.match(policy, /connect-src|isAllowed/)
  assert.match(policy, /appassets\.androidplatform\.net/)
  assert.match(policy, /getQueryParameterNames/)
  assert.doesNotMatch(policy, /addJavascriptInterface/)
  assert.doesNotMatch(policy, /HttpURLConnection|FileInputStream|StageCraftNative/)
})

test('Android cleartext access requires the explicit UI risk switch and strict native validation', () => {
  const manifest = read('app', 'src', 'main', 'AndroidManifest.xml')
  const html = read('app', 'src', 'main', 'assets', 'index.html')
  const renderer = read('app', 'src', 'main', 'assets', 'renderer.js')
  const validator = read('app', 'src', 'main', 'java', 'ai', 'stagecraft', 'android', 'ServerAddressValidator.java')
  assert.match(manifest, /android:usesCleartextTraffic="true"/)
  assert.match(html, /value="https:\/\/"/)
  assert.match(html, /id="allow-http" type="checkbox"/)
  assert.match(html, /HTTP 不加密/)
  assert.ok(renderer.includes("bridge.pair(byId('server-address').value.trim(), byId('allow-http').checked"))
  assert.match(validator, /scheme\.equals\("http"\) && !allowInsecureHttp/)
  for (const forbidden of ['getUserInfo()', 'getQuery()', 'getFragment()']) assert.ok(validator.includes(forbidden))
})

test('Android credentials stay native, encrypted, and out of URLs or Javascript', () => {
  const store = read('app', 'src', 'main', 'java', 'ai', 'stagecraft', 'android', 'RemoteSessionStore.java')
  const connection = read('app', 'src', 'main', 'java', 'ai', 'stagecraft', 'android', 'RemoteCoreConnection.java')
  const bridge = read('app', 'src', 'main', 'java', 'ai', 'stagecraft', 'android', 'NativeBridge.java')
  const renderer = read('app', 'src', 'main', 'assets', 'renderer.js')
  assert.match(store, /AndroidKeyStore/)
  assert.match(store, /AES\/GCM\/NoPadding/)
  assert.match(store, /new JSONObject\(\)\.put\("address", address\).*put\("credential", credential\)/)
  assert.match(store, /session_ciphertext/)
  assert.match(store, /session_iv/)
  assert.doesNotMatch(store, /putString\([^\n]*(token|credential)/i)
  assert.match(store, /\.commit\(\)/)
  assert.match(connection, /setRequestProperty\("Authorization", "Bearer " \+ credential\)/)
  assert.match(connection, /setInstanceFollowRedirects\(false\)/)
  assert.doesNotMatch(connection, /[?&](token|session)=/i)
  assert.doesNotMatch(bridge, /(Log\.|System\.out|printStackTrace)/)
  assert.doesNotMatch(renderer, /(localStorage|document\.cookie|Bearer|token)/)
  assert.match(bridge, /JSONObject\.quote\(messageJson\)/)
  assert.match(bridge, /result == null \? JSONObject\.NULL\.toString\(\) : result\.toString\(\)/)
  const operations = read('app', 'src', 'main', 'java', 'ai', 'stagecraft', 'android', 'AndroidCompositionOperations.java')
  assert.match(operations, /roomFromStory\(roomId, new JSONObject\(readStoryText\("eldoria"\)\)\)/)
  assert.match(operations, /repository\.putRecord\("story-packages", id, story\)/)
  assert.match(operations, /repository\.getRecord\("story-packages", id\)/)
  assert.match(operations, /"story\.create"\.equals\(operation\)/)
  assert.match(operations, /"restartRoom"\.equals\(method\)/)
  assert.match(operations, /options\.getString\("mode"\)/)
  assert.match(operations, /isLegacyPlaceholder\(room\)/)
  assert.doesNotMatch(operations, /Music drifts through the royal festival hall/)
  assert.doesNotMatch(bridge, /asyncGeneration/)
  assert.match(bridge, /if \(!closed\) deliverAsync\(callbackId, result\.toString\(\)\)/)
})

test('Android APK defaults to the packaged full Web UI while retaining remote entry points', () => {
  const activity = read('app', 'src', 'main', 'java', 'ai', 'stagecraft', 'android', 'MainActivity.java')
  assert.match(activity, /showLocalUi\(\);/)
  assert.match(activity, /localServer\.urlFor\("\/web\/local\.html"\)/)
  assert.match(activity, /LOCAL_ORIGIN \+ "\/web\/local\.html"/)
  assert.match(activity, /void showRemoteUi\(String address\)/)
  assert.match(activity, /void showPairingPage\(\)/)
  const client = read('app', 'src', 'main', 'java', 'ai', 'stagecraft', 'android', 'StageCraftWebViewClient.java')
  assert.match(client, /contentType\.indexOf\(';'\)/)
  assert.match(client, /contentType\.substring\(0, parameter\)\.trim\(\)/)
  assert.match(client, /new WebResourceResponse\(mime, encoding, input\)/)
  const onCreate = activity.slice(activity.indexOf('onCreate('), activity.indexOf('/** Open the packaged full Web UI'))
  assert.doesNotMatch(onCreate, /index\.html\?mode=remote/)
})

test('built Android APK contains the verified embedded Core and full Web UI assets', () => {
  const apk = join(android, 'app', 'build', 'outputs', 'apk', 'debug', 'app-debug.apk')
  if (!existsSync(apk)) return
  const bytes = readFileSync(apk)
  const zipNames = bytes.toString('latin1')
  for (const asset of [
    'assets/embedded-core.js', 'assets/embedded-core.json', 'assets/index.html', 'assets/renderer.js',
    'assets/web/local.html', 'assets/web/index.html', 'assets/web/app.js', 'assets/web/style.css',
    'assets/web/core-client.js', 'assets/web/local-runtime-web-entry.js',
  ]) {
    assert.ok(zipNames.includes(asset), `missing ${asset} from APK`)
  }
})

test('Android embedded Core is generated, verified, and selected locally', () => {
  const readme = readFileSync(join(android, 'README.md'), 'utf8')
  const bridge = read('app', 'src', 'main', 'java', 'ai', 'stagecraft', 'android', 'NativeBridge.java')
  const verifier = read('app', 'src', 'main', 'java', 'ai', 'stagecraft', 'android', 'EmbeddedCoreArtifact.java')
  const activity = read('app', 'src', 'main', 'java', 'ai', 'stagecraft', 'android', 'MainActivity.java')
  const operations = read('app', 'src', 'main', 'java', 'ai', 'stagecraft', 'android', 'AndroidCompositionOperations.java')
  const gradle = read('app', 'build.gradle.kts')
  const entrypoint = readFileSync(join(root, 'src', 'portable', 'android-core.ts'), 'utf8')
  assert.match(readme, /embedded-core\.js/)
  assert.match(readme, /shared StageCraft solution composition/)
  assert.match(readme, /model gateway, SQLite repository, Cordis services/)
  assert.match(bridge, /localCoreAllowed/)
  assert.match(bridge, /embeddedCore\.valid\(\)/)
  assert.match(verifier, /SHA-256/)
  assert.match(verifier, /EXPECTED_PROTOCOL/)
  assert.match(verifier, /EXPECTED_BUNDLE/)
  assert.match(activity, /EmbeddedCoreArtifact\.verify/)
  assert.match(gradle, /buildEmbeddedCore/)
  assert.match(gradle, /packageEmbeddedCore/)
  assert.match(gradle, /verifyEmbeddedCoreAssets/)
  assert.match(gradle, /SHA-256/)
  assert.match(gradle, /generated\/android-assets/)
  assert.match(gradle, /inputs\.file\(coreBuildScript\)/)
  assert.match(gradle, /inputs\.dir\(coreSourceRoot\)/)
  assert.match(gradle, /--output-dir/)
  assert.match(gradle, /embedded-core\.js.*embedded-core\.json/s)
  assert.doesNotMatch(gradle, /prompts\/prompts\.json/)
  assert.match(gradle, /stories\/\*\.json/)
  assert.match(entrypoint, /createAndroidComposition/)
  assert.match(entrypoint, /StageCraftEmbeddedCore/)
  assert.match(entrypoint, /requires the native operations bridge/)
  assert.match(read('app', 'src', 'main', 'assets', 'index.html'), /embedded-core\.js/)
  assert.match(read('app', 'src', 'main', 'assets', 'renderer.js'), /embedded\.start\(message => renderer\.receive\(message\)\)/)
  assert.doesNotMatch(bridge, /installLocalCore|CoreHost/)
  assert.match(operations, /stagecraft\.room\.get/)
  assert.match(operations, /stagecraft\.repository/)
  assert.match(operations, /core-state\.commit/)
})


test('Android exports only current objects through SAF and persists prompt presets', () => {
  const activity = read('app', 'src', 'main', 'java', 'ai', 'stagecraft', 'android', 'MainActivity.java')
  const bridge = read('app', 'src', 'main', 'java', 'ai', 'stagecraft', 'android', 'NativeBridge.java')
  const operations = read('app', 'src', 'main', 'java', 'ai', 'stagecraft', 'android', 'AndroidCompositionOperations.java')
  const runtime = read('app', 'src', 'main', 'assets', 'web', 'local-runtime-web-entry.js')
  assert.match(activity, /Intent\.ACTION_CREATE_DOCUMENT/)
  assert.match(activity, /Intent\.ACTION_OPEN_DOCUMENT/)
  assert.match(activity, /OPEN_STORY_DOCUMENT/)
  assert.match(activity, /CREATE_EXPORT_DOCUMENT/)
  assert.match(bridge, /@JavascriptInterface public void chooseStoryArchive/)
  assert.match(bridge, /compositionOperations\.importStoryArchive/)
  assert.match(bridge, /@JavascriptInterface public void exportDocument/)
  assert.match(bridge, /compositionOperations\.exportStoryArchive/)
  assert.match(operations, /repository\.listAssets\("\/story-assets\/" \+ id \+ "\/"\)/)
  assert.match(operations, /repository\.importStory\(id, story, assets\)/)
  assert.match(operations, /"stagecraft-story"\.equals\(manifest\.optString\("format"\)\)/)
  assert.match(operations, /rewritePortraitRefs\(story, id\)/)
  const resolver = read('app', 'src', 'main', 'java', 'ai', 'stagecraft', 'android', 'LocalAssetResolver.java')
  assert.match(resolver, /repository\.getAsset\("\/story-assets\/" \+ id \+ "\/" \+ file\)/)
  assert.match(operations, /repository\.putRecord\("prompt-presets", id, preset\)/)
  assert.match(runtime, /nativeInvokeSync\('preset\.list'/)
  assert.match(runtime, /nativeInvokeSync\('preset\.save'/)
  assert.match(runtime, /nativeInvokeSync\('preset\.delete'/)
  assert.doesNotMatch(runtime, /'\/api\/prompts\/presets': '提示词预设编辑'/)
})

test('Android native connection establishes SSE before view and never retries commands', () => {
  const connection = read('app', 'src', 'main', 'java', 'ai', 'stagecraft', 'android', 'RemoteCoreConnection.java')
  const openStream = connection.slice(connection.indexOf('private void openStream'), connection.indexOf('private void scheduleReconnect'))
  assert.ok(openStream.indexOf('open("/api/core/events"') < openStream.indexOf('requestView(currentGeneration)'))
  assert.ok(openStream.indexOf('emitState("connected"') < openStream.indexOf('emitResync(reason'))
  const dispatch = connection.slice(connection.indexOf('public void dispatch'), connection.indexOf('private void openStream'))
  assert.match(dispatch, /\/api\/core\/commands/)
  assert.doesNotMatch(dispatch, /scheduleReconnect|retryExecutor/)
  assert.match(connection, /backoff\.delayForAttempt/)
  assert.match(connection, /activeRequests/)
  assert.match(connection, /public synchronized void pause\(\)/)
  assert.match(connection, /public synchronized void resume\(\)/)
  assert.match(read('app', 'src', 'main', 'assets', 'renderer.js'), /bridge\.disconnect\(\)/)
  assert.match(read('app', 'src', 'main', 'assets', 'renderer.js'), /reconnecting: '正在重连'/)
})

test('Android media and PNG import remain native, bounded, authenticated, and packaged reproducibly', () => {
  const appGradle = read('app', 'build.gradle.kts')
  const connection = read('app', 'src', 'main', 'java', 'ai', 'stagecraft', 'android', 'RemoteCoreConnection.java')
  const bridge = read('app', 'src', 'main', 'java', 'ai', 'stagecraft', 'android', 'NativeBridge.java')
  const activity = read('app', 'src', 'main', 'java', 'ai', 'stagecraft', 'android', 'MainActivity.java')
  const policy = read('app', 'src', 'main', 'java', 'ai', 'stagecraft', 'android', 'RemoteAssetPolicy.java')
  const renderer = read('app', 'src', 'main', 'assets', 'renderer.js')
  assert.match(appGradle, /packageRemoteRenderer/)
  assert.match(appGradle, /include\("index\.html", "styles\.css", "renderer\.js",/)
  assert.match(appGradle, /from\(rootProject\.projectDir\.parentFile\.resolve\("stories\/default"\)\) \{ into\("stories\/default"\) \}/)
  assert.match(appGradle, /stories\/default\/\*\.json/)
  assert.doesNotMatch(appGradle, /stories\/custom\/\*\.json/)
  assert.match(appGradle, /include\("index\.html", "styles\.css", "renderer\.js", "embedded-core\.js", "embedded-core\.json", "version\.json", "prompts\/\*\*", "stories\/\*\*", "web\/\*\*"\)/)
  assert.match(appGradle, /generateVersionInfo/)
  assert.match(appGradle, /versionName = releaseVersion/)
  assert.match(appGradle, /from\(generatedWebUi\) \{ into\("web"\); include\("\*\*\/\*"\) \}/)
  assert.match(appGradle, /generateLocalEntry/)
  assert.match(appGradle, /preBuild.*dependsOn\(verifyEmbeddedCoreAssets\)/s)
  assert.match(connection, /public void loadMedia/)
  assert.match(connection, /RemoteAssetPolicy\.requireAssetPath/)
  assert.match(connection, /setInstanceFollowRedirects\(false\)/)
  assert.match(connection, /public void importCharacterCard/)
  assert.match(connection, /"\/api\/st-cards\/import"/)
  assert.match(policy, /MAX_BYTES = 2 \* 1024 \* 1024/)
  assert.match(policy, /\^\/assets\//)
  assert.doesNotMatch(policy, /svg/)
  assert.match(activity, /setType\("image\/png"\)/)
  assert.match(bridge, /isPng\(bytes\)/)
  assert.match(bridge, /8 \* 1024 \* 1024/)
  assert.match(renderer, /bridge\.loadMedia/)
  assert.match(renderer, /bridge\.chooseCharacterCard\(\)/)
  assert.doesNotMatch(renderer, /FileReader|arrayBuffer/)
  const localRuntimeEntry = readFileSync(join(root, 'android', 'app', 'src', 'main', 'assets', 'web', 'local-runtime-web-entry.js'), 'utf8')
  assert.doesNotMatch(localRuntimeEntry, /local-adapter/)
  assert.match(localRuntimeEntry, /\(method === 'GET' \|\| method === 'DELETE'\) \? handler\(url\.searchParams\) : handler\(body\)/)
  assert.doesNotMatch(localRuntimeEntry, /handler\(url\.searchParams, body\)/)
  assert.match(localRuntimeEntry, /'\/api\/story\/save'/)
  assert.match(localRuntimeEntry, /'\/api\/story\/save-as'/)
  assert.match(localRuntimeEntry, /'\/api\/stories': \(body\)/)
  assert.match(localRuntimeEntry, /nativeInvokeSync\('story\.create'/)
  assert.match(localRuntimeEntry, /nativeInvokeSync\('story\.save'/)
  const localCore = readFileSync(join(root, 'src', 'portable', 'android-local-core.ts'), 'utf8')
  assert.match(localCore, /'story\.read'/)
  assert.match(localCore, /Promise\.resolve\(invokeSync\('story\.read'/)
  assert.match(localRuntimeEntry, /nativeInvokeSync\('story\.saveAs'/)
  assert.match(localRuntimeEntry, /nativeInvokeSync\('story\.delete'/)
  assert.match(localRuntimeEntry, /story\.create/)
  assert.match(localRuntimeEntry, /'\/api\/restart': async \(body\)/)
  const style = readFileSync(join(root, 'public', 'style.css'), 'utf8')
  assert.match(style, /\.creator-workbench-story-pick\{display:flex;order:2;flex:1 1 100%/)
  assert.doesNotMatch(style, /@media \(max-width:680px\)\{\.creator-workbench-story-pick\{display:none\}\}/)
})

test('desktop pairing-code operator entry is loopback-only and visible in settings', () => {
  const policy = readFileSync(join(root, 'src', 'remote-access.ts'), 'utf8')
  const html = readFileSync(join(root, 'public', 'index.html'), 'utf8')
  const app = readFileSync(join(root, 'public', 'app.js'), 'utf8')
  assert.match(policy, /\/api\/remote\/pairing-code/)
  assert.match(policy, /!isLoopbackAddress\(request\.socket\.remoteAddress\)/)
  assert.match(html, /id="remote-pairing-code"/)
  assert.match(html, /RP_REMOTE=1/)
  assert.match(html, /id="remote-pairing-revoke"/)
  assert.match(app, /fetch\('\/api\/remote\/pairing-code', \{ method: 'POST'/)
})

test('APK sync flow: confirm-driven pull/push over an authenticated native bridge', () => {
  const bridge = read('app', 'src', 'main', 'java', 'ai', 'stagecraft', 'android', 'NativeBridge.java')
  const runtime = readFileSync(join(root, 'android', 'app', 'src', 'main', 'assets', 'web', 'local-runtime-web-entry.js'), 'utf8')
  const app = readFileSync(join(root, 'public', 'app.js'), 'utf8')
  const html = readFileSync(join(root, 'public', 'index.html'), 'utf8')
  const boot = readFileSync(join(root, 'src', 'app-boot.ts'), 'utf8')
  assert.match(bridge, /@JavascriptInterface public String syncStatus\(\)/)
  assert.match(bridge, /@JavascriptInterface public void syncPair\(/)
  assert.match(bridge, /@JavascriptInterface public void syncRemoteFetch\(/)
  assert.match(bridge, /\/api\/remote\/sync/)
  assert.match(bridge, /"Authorization", "Bearer " \+ saved\.credential\(\)/)
  assert.match(bridge, /sessionStore\.clearSession\(\)/)
  // 回调必须传对象字面量，不可用 JSONObject.quote 包成字符串（网页端 result.ok 会失效）
  assert.match(bridge, /StageCraftSyncPairResult && window\.StageCraftSyncPairResult\(" \+ resultJson \+ "\)/)
  assert.match(bridge, /StageCraftSyncFetchResult && window\.StageCraftSyncFetchResult\(" \+ result\.toString\(\) \+ "\)/)
  assert.match(runtime, /window\.StageCraftSyncRemote = syncRemote/)
  assert.match(runtime, /function parseNativeResult/)
  assert.match(runtime, /refreshActiveProvider/)
  assert.match(runtime, /payload\.providers\.defaults/)
  assert.match(runtime, /providers\.filter\(item => item\.id !== id\)/)
  assert.match(runtime, /window\.StageCraftSyncFetchResult = result =>/)
  assert.match(runtime, /window\.StageCraftSyncPairResult = result =>/)
  assert.match(runtime, /syncRemoteFetch\('GET'\)/)
  assert.match(runtime, /syncRemoteFetch\('PUT'/)
  assert.match(runtime, /'stagecraft\.repository', \{ method: 'importRoom'/)
  assert.match(runtime, /nativeInvokeSync\('preset\.save'/)
  assert.match(app, /\$\('#sync-remote-pull'\)\.onclick/)
  assert.match(app, /\$\('#sync-remote-push'\)\.onclick/)
  assert.match(app, /sync\.remote\.address/)
  assert.match(app, /remote-pairing-section/)
  const syncStyle = readFileSync(join(root, 'public', 'style.css'), 'utf8')
  assert.match(syncStyle, /sync-remote-actions\{display:flex;flex-direction:column/)
  assert.match(app, /confirm\('从电脑拉取/)
  assert.match(app, /confirm\('推送到电脑/)
  assert.match(html, /id="sync-remote-row"/)
  assert.match(html, /id="sync-remote-pull"/)
  assert.match(html, /与电脑同步（APK）/)
  assert.match(html, /手机 APK 配对后/)
  assert.match(boot, /\/api\/remote\/sync/)
  assert.match(boot, /updatePromptPreset\(preset as any, promptsFilePath\)/)
})

test('Android local prompt IO: bundled gameplay data source plus SQLite preset persistence', () => {
  const operations = read('app', 'src', 'main', 'java', 'ai', 'stagecraft', 'android', 'AndroidCompositionOperations.java')
  const buildScript = readFileSync(join(root, 'scripts', 'build-android-core.mjs'), 'utf8')
  const bundled = readFileSync(join(root, 'src', 'portable', 'bundled-gameplay.ts'), 'utf8')
  const localCore = readFileSync(join(root, 'src', 'portable', 'android-local-core.ts'), 'utf8')
  const runtime = readFileSync(join(root, 'android', 'app', 'src', 'main', 'assets', 'web', 'local-runtime-web-entry.js'), 'utf8')
  const appGradle = read('app', 'build.gradle.kts')
  assert.match(operations, /"preset\.active-scope\.set"/)
  assert.match(operations, /"prompt-meta"/)
  assert.match(buildScript, /android-node-builtin-stubs/)
  assert.match(buildScript, /node:fs/)
  assert.match(bundled, /with \{ type: 'json' \}/)
  assert.match(localCore, /setPromptStorage\(createAndroidPromptStorage\(/)
  assert.match(runtime, /preset\.active-scope\.set/)
  assert.match(runtime, /userEditable === true/)
  assert.match(appGradle, /prompts\/gameplay/)
  // 双端共用同一生成内核：第二套自包含提示词 workers 已删除
  assert.equal(existsSync(join(root, 'src', 'portable', 'local-workers.ts')), false)
  assert.match(localCore, /createRealWorkers\(/)
  assert.doesNotMatch(localCore, /createLocalWorkers/)
  // 版本记录与更新：version.json 注入、/api/update/check、原生安装桥、安装权限
  const manifest = read('app', 'src', 'main', 'AndroidManifest.xml')
  const bridge = read('app', 'src', 'main', 'java', 'ai', 'stagecraft', 'android', 'NativeBridge.java')
  const appBoot = readFileSync(join(root, 'src', 'app-boot.ts'), 'utf8')
  const appJs = readFileSync(join(root, 'public', 'app.js'), 'utf8')
  const indexHtml = readFileSync(join(root, 'public', 'index.html'), 'utf8')
  assert.match(appGradle, /generateVersionInfo/)
  assert.match(appGradle, /versionName = releaseVersion/)
  assert.match(manifest, /REQUEST_INSTALL_PACKAGES/)
  assert.match(bridge, /updateDownloadAndInstall/)
  assert.match(bridge, /PackageInstaller/)
  assert.match(bridge, /deliverUpdateProgress/)
  assert.match(bridge, /StageCraftUpdateProgress/)
  assert.match(bridge, /installResultReceiver/)
  assert.match(bridge, /STATUS_PENDING_USER_ACTION/)
  assert.match(bridge, /getParcelableExtra\(Intent\.EXTRA_INTENT/)
  assert.match(bridge, /context\.startActivity\(confirmation\)/)
  assert.match(bridge, /PendingIntent\.FLAG_MUTABLE/)
  assert.doesNotMatch(bridge, /getBroadcast\([^\n]+PendingIntent\.FLAG_IMMUTABLE/)
  assert.match(bridge, /Context\.RECEIVER_NOT_EXPORTED/)
  assert.match(bridge, /killProcess\(android\.os\.Process\.myPid\(\)\)/)
  assert.match(bridge, /STATUS_SUCCESS/)
  assert.match(bridge, /AlarmManager/)
  assert.match(bridge, /am\.set\(AlarmManager\.RTC/)
  assert.match(runtime, /'\/api\/version'/)
  assert.match(runtime, /'\/api\/update\/check'/)
  assert.match(runtime, /local\.billing\.prices/)
  assert.match(runtime, /billing: billingPrices \? \{ prices: billingPrices \} : null/)
  assert.match(runtime, /preferred\.selectedModel \?\? preferred\.model/)
  assert.match(appBoot, /billing: \{ prices: billing\.getPrices\(\) \}/)
  assert.match(appBoot, /billing\.savePrices\(body\.billing\.prices/)
  assert.match(appBoot, /'\/api\/stream'/)
  assert.match(appJs, /new EventSource\('\/api\/stream'\)/)
  assert.match(appBoot, /'\/api\/update\/check'/)
  assert.match(appBoot, /'\/api\/version'/)
  assert.match(appJs, /checkForUpdatesSilent/)
  assert.match(appJs, /该版本没有可用的 Android 安装包/)
  assert.match(appJs, /settings-auto-update/)
  assert.match(indexHtml, /id="check-update"/)
  assert.match(indexHtml, /id="about-version"/)
})

// 防分叉：TS 权威清单 STAGECRAFT_REPOSITORY_METHODS 的每个方法都必须在 Android 原生实现里存在
test('Android repository mirrors every STAGECRAFT_REPOSITORY_METHODS method (no IO fork)', async () => {
  const { STAGECRAFT_REPOSITORY_METHODS } = await import('../src/stagecraft-repository.ts')
  const java = read('app', 'src', 'main', 'java', 'ai', 'stagecraft', 'android', 'AndroidCompositionOperations.java')
  const missing = STAGECRAFT_REPOSITORY_METHODS.filter(method => !java.includes(`"${method}".equals(method)`))
  assert.deepEqual(missing, [], `Android 原生缺这些 repository 方法（会导致「不支持安卓xxx」）：${missing.join(', ')}`)
})
